# Home Page
home.title=Welcome to Spring Boot MVC
home.link=Register Customer

# Customer Registration Form
cust.form.title=Welcome to the Customer Registration Page
cust.form.label1=Customer Number
cust.form.label2=Customer Name
cust.form.label3=Customer Address
cust.form.label4=Register Customer